# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flashy-tt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6708a0b8d0e64a2aaaa1a519c9290a95 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_dd935a8fdb544a1e8d647e2f43e07604 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6708a0b8d0e64a2aaaa1a519c9290a95 }}/chamoli2k2/flashy-tt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flashy-tt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_251aa955f52f41758c5f358627a45669 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6708a0b8d0e64a2aaaa1a519c9290a95 }}/chamoli2k2/flashy-tt:${{ github.sha }}'